// <auto-generated />
using System;
using Itau.Investimentos.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Itau.Investimentos.Infrastructure.Migrations
{
    [DbContext(typeof(ItauInvestimentosDbContext))]
    [Migration("20250608024714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Itau.Investimentos.Core.Ativo", b =>
                {
                    b.Property<int>("AtiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AtiId"));

                    b.Property<string>("AtiCodigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AtiNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AtiId");

                    b.ToTable("Ativos");
                });

            modelBuilder.Entity("Itau.Investimentos.Core.Cotacao", b =>
                {
                    b.Property<int>("CotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CotId"));

                    b.Property<int?>("AtivoAtiId")
                        .HasColumnType("int");

                    b.Property<int>("CotAtiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CotDataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CotPrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("CotId");

                    b.HasIndex("AtivoAtiId");

                    b.ToTable("Cotacoes");
                });

            modelBuilder.Entity("Itau.Investimentos.Core.Operacao", b =>
                {
                    b.Property<int>("OprId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OprId"));

                    b.Property<int?>("AtivoAtiId")
                        .HasColumnType("int");

                    b.Property<int>("OprAtiId")
                        .HasColumnType("int");

                    b.Property<decimal>("OprCorretagem")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("OprDataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("OprPrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("OprQuantidade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("OprTipoOperacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OprUsuId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioUsuId")
                        .HasColumnType("int");

                    b.HasKey("OprId");

                    b.HasIndex("AtivoAtiId");

                    b.HasIndex("UsuarioUsuId");

                    b.ToTable("Operacoes");
                });

            modelBuilder.Entity("Itau.Investimentos.Core.Posicao", b =>
                {
                    b.Property<int>("PosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PosId"));

                    b.Property<int?>("AtivoAtiId")
                        .HasColumnType("int");

                    b.Property<int>("PosAtiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PosDataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PosPrecoMedio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PosQuantidade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PosUsuId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioUsuId")
                        .HasColumnType("int");

                    b.HasKey("PosId");

                    b.HasIndex("AtivoAtiId");

                    b.HasIndex("UsuarioUsuId");

                    b.ToTable("Posicoes");
                });

            modelBuilder.Entity("Itau.Investimentos.Core.Usuario", b =>
                {
                    b.Property<int>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UsuId"));

                    b.Property<string>("UsuEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("UsuPercentualCorretagem")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("UsuId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Itau.Investimentos.Core.Cotacao", b =>
                {
                    b.HasOne("Itau.Investimentos.Core.Ativo", "Ativo")
                        .WithMany()
                        .HasForeignKey("AtivoAtiId");

                    b.Navigation("Ativo");
                });

            modelBuilder.Entity("Itau.Investimentos.Core.Operacao", b =>
                {
                    b.HasOne("Itau.Investimentos.Core.Ativo", "Ativo")
                        .WithMany()
                        .HasForeignKey("AtivoAtiId");

                    b.HasOne("Itau.Investimentos.Core.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioUsuId");

                    b.Navigation("Ativo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Itau.Investimentos.Core.Posicao", b =>
                {
                    b.HasOne("Itau.Investimentos.Core.Ativo", "Ativo")
                        .WithMany()
                        .HasForeignKey("AtivoAtiId");

                    b.HasOne("Itau.Investimentos.Core.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioUsuId");

                    b.Navigation("Ativo");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
